# Enable AndroidX
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Increase memory for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
# Enable parallel builds
org.gradle.parallel=true

# Set Java Home for IDE and Gradle builds
org.gradle.java.home=C:/Users/mohdk/.jdks/jbr-17.0.14


# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
